name: game_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flame_forge2d: ^0.14.0


  cupertino_icons: ^1.0.2
  flame: ^1.7.3
  flutter_riverpod: ^2.3.6
  flame_tiled: ^1.10.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  window_manager: ^0.3.4
  flutter_animate: ^4.2.0
  uuid: ^3.0.7
  recase: ^4.1.0
  flame_audio: ^1.4.1
  infinite_carousel: ^1.0.3
  numerus: ^2.1.2

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.5


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/enemy_sprites/
    - assets/images/enemy_sprites/mushroomBoomer/
    - assets/images/enemy_sprites/mushroomBurrower/
    - assets/images/enemy_sprites/mushroomHopper/
    - assets/images/enemy_sprites/mushroomShooter/
    - assets/images/enemy_sprites/mushroomRunner/
    - assets/images/enemy_sprites/mushroomSpinner/


    - assets/images/attribute_sprites/

    - assets/images/weapons/
    - assets/images/weapons/charge/
    - assets/images/weapons/melee/
    - assets/images/weapons/projectiles/
    - assets/images/weapons/projectiles/bullets/
    - assets/images/weapons/projectiles/blasts/

    - assets/images/entity_effects/



    - assets/images/powerups/
    - assets/images/portal/
    - assets/images/sprites/
    - assets/images/status_effects/
    - assets/images/effects/
    - assets/images/ui/
    - assets/images/buttons/
    - assets/images/background/
    - assets/images/decorations/
    - assets/images/experience/

    - assets/images/attributes/
    - assets/tiles/
    - assets/audio/sfx/
    - assets/audio/sfx/projectiles/
    - assets/audio/


    - assets/images/
    - assets/fonts/
    - assets/


  fonts:
    - family: HeroSpeak
      fonts:
        - asset: assets/fonts/hero-speak.ttf
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/yusei-magic.ttf  
    - family: Alagard
      fonts:
        - asset: assets/fonts/alagard.ttf