name: test_game_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flame: ^1.8.1
  flame_spine: ^0.1.1
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2
  texture_rgba_renderer: ^0.0.16



assets:
    - assets/
    - assets/spine/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  shaders:
    - packages/flutter_shaders/shaders/pixelation.frag
