name: runefire
description: A magic themed roguelike game, utilizing maigc, swords and guns to destory otherworldly creatures.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flame: ^1.7.3
  flutter_riverpod: ^2.3.6
  flame_tiled: ^1.10.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.15
  window_manager: ^0.3.4
  flutter_animate: ^4.2.0
  uuid: ^3.0.7
  recase: ^4.1.0
  flame_audio: ^1.4.1
  numerus: ^2.1.2
  particle_field: ^1.0.0
  rnd: ^0.2.0
  flame_forge2d: ^0.15.0
  simple_shadow: ^0.3.1
  image_size_getter: ^2.1.2
  infinite_carousel: ^1.0.3
  win32_gamepad: ^1.0.7

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.5


  flutter_lints: ^2.0.0
  test: ^1.24.3

flutter:

  uses-material-design: true

  assets:
    - assets/audio/
    - assets/audio/sfx/
    - assets/audio/sfx/magic/
    - assets/audio/sfx/magic/power_word/
    - assets/audio/sfx/projectile/
    - assets/fonts/
    - assets/images/
    - assets/images/attributes/
    - assets/images/attribute_sprites/
    - assets/images/background/
    - assets/images/background/runes/
    - assets/images/effects/
    - assets/images/enemy_sprites/
    - assets/images/enemy_sprites/mushroomBoomer/
    - assets/images/enemy_sprites/mushroomBurrower/
    - assets/images/enemy_sprites/mushroomHopper/
    - assets/images/enemy_sprites/mushroomRunner/
    - assets/images/enemy_sprites/mushroomShooter/
    - assets/images/enemy_sprites/mushroomSpinner/
    - assets/images/entity_effects/
    - assets/images/expendables/
    - assets/images/experience/
    - assets/images/icons/
    - assets/images/powerups/
    - assets/images/secondary_icons/
    - assets/images/sprites/
    - assets/images/sprites/runeknight/
    - assets/images/status_effects/
    - assets/images/ui/
    - assets/images/ui/ammo/
    - assets/images/ui/permanent_attributes/
    - assets/images/weapons/
    - assets/images/weapons/charge/
    - assets/images/weapons/melee/
    - assets/images/weapons/projectiles/
    - assets/images/weapons/projectiles/blasts/
    - assets/images/weapons/projectiles/bullets/
    - assets/images/weapons/projectiles/magic/

  # assets end


  fonts:
    - family: HeroSpeak
      fonts:
        - asset: assets/fonts/hero-speak.ttf
    - family: YuseiMagic
      fonts:
        - asset: assets/fonts/yusei-magic.ttf  
    - family: Alagard
      fonts:
        - asset: assets/fonts/alagard.ttf